parameters:
#    blogger_general.example.class: Blogger\GeneralBundle\Example

services:
#    blogger_general.example:
#        class: %blogger_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
